<?php require __DIR__.'/../controladores/habitaciones.php'; require __DIR__.'/../includes/header.php'; ?>
<?php if (!$fatal): ?>
<?php if ($accion === 'listar'): ?>
<div class="heading"><div><div class="eyebrow">INVENTARIO Y DISPONIBILIDAD</div><h1>Habitaciones</h1><p>Administra los espacios y consulta su ocupación actual.</p></div><a class="button primary" href="?accion=crear">＋ Nueva habitación</a></div>
<div class="stats">
<?php foreach (['TOTAL'=>'Total de habitaciones','DISPONIBLE'=>'Disponibles','OCUPADA'=>'Ocupadas','MANTENIMIENTO'=>'En mantenimiento'] as $key=>$label): $n=$key==='TOTAL'?count($todas):count(array_filter($todas,fn($h)=>$h['estado']===$key)); ?>
<div class="stat"><span><?= e($label) ?></span><strong><?= $n ?></strong><small><?= $key==='TOTAL' ? 'Inventario completo' : 'Según el estado registrado' ?></small></div>
<?php endforeach ?></div>
<section class="panel"><div class="panel-title"><h2>Listado de habitaciones</h2><span><?= count($filas) ?> resultado<?= count($filas)!==1?'s':'' ?></span></div>
<form class="filters" method="get"><div class="search"><label for="q">Buscar habitación</label><input id="q" name="q" placeholder="Número o código…" value="<?= e($q) ?>" maxlength="10"></div>
<div><label for="estado">Estado</label><select id="estado" name="estado"><option value="">Todos los estados</option><?php foreach(Habitacion::ESTADOS as $s): ?><option value="<?= e($s) ?>" <?= $estado===$s?'selected':'' ?>><?= e(ucfirst(strtolower($s))) ?></option><?php endforeach ?></select></div>
<div><label for="piso">Piso</label><input type="number" min="1" max="2147483647" name="piso" id="piso" placeholder="Todos" value="<?= e($piso) ?>"></div><button class="button primary">Filtrar</button><a class="clear" href="habitaciones.php">Limpiar</a></form>
<div class="table-wrap"><table><thead><tr><th>Habitación</th><th>Piso</th><th>Ocupación activa</th><th>Estado</th><th>Observaciones</th><th>Acciones</th></tr></thead><tbody>
<?php foreach($filas as $h): $bloqueada=$h['estado']==='OCUPADA'||$h['activos']>0; ?>
<tr><td><span class="room-icon" aria-hidden="true">▦</span><strong><?= e($h['numero']) ?></strong></td><td><?= e($h['piso']) ?></td><td><strong><?= e($h['activos']) ?></strong><span class="muted"> / <?= e($h['capacidad']) ?> plazas</span><?php if($h['activos']>$h['capacidad']): ?><small class="warning">Excede la capacidad</small><?php endif ?></td><td><span class="badge <?= e(strtolower($h['estado'])) ?>"><?= e(ucfirst(strtolower($h['estado']))) ?></span></td><td class="observaciones"><?= e(($h['observaciones'] === null || $h['observaciones'] === '') ? 'Sin observaciones' : $h['observaciones']) ?></td><td><div class="actions"><a class="edit" href="?accion=editar&amp;id=<?= (int)$h['id_habitacion'] ?>" aria-label="Editar habitación <?= e($h['numero']) ?>">Editar</a><?php if($bloqueada): ?><button class="disabled" disabled title="No se puede eliminar una habitación ocupada o con residentes activos.">Eliminar</button><?php else: ?><a class="delete" href="?accion=eliminar&amp;id=<?= (int)$h['id_habitacion'] ?>" aria-label="Eliminar habitación <?= e($h['numero']) ?>">Eliminar</a><?php endif ?></div></td></tr>
<?php endforeach ?>
<?php if(!$filas): ?><tr><td colspan="6" class="empty"><h3>No se encontraron habitaciones</h3><p>Prueba con otro número, estado o piso.</p><a href="habitaciones.php">Ver todas las habitaciones</a></td></tr><?php endif ?>
</tbody></table></div><div class="table-note">La eliminación está bloqueada para habitaciones ocupadas o con residentes activos.</div></section>
<?php elseif($accion === 'crear' || $accion === 'editar'): ?>
<div class="heading"><div><div class="eyebrow">INVENTARIO DE HABITACIONES</div><h1><?= e($titulo) ?></h1><p><?= $accion==='crear'?'Completa los datos para agregar un espacio a la residencia.':'Actualiza los datos y el estado de esta habitación.' ?></p></div><a class="button secondary" href="habitaciones.php">← Volver al listado</a></div>
<div class="form-layout"><section class="panel form-panel"><h2>Datos de la habitación</h2><p class="muted">Los campos con * son obligatorios.</p>
<form method="post"><?= csrf() ?><div class="form-grid">
<?php foreach(['numero'=>'Número o código','piso'=>'Piso','capacidad'=>'Capacidad'] as $campo=>$label): ?><div><label for="<?= $campo ?>"><?= $label ?> *</label><input id="<?= $campo ?>" name="<?= $campo ?>" type="<?= $campo==='numero'?'text':'number' ?>" <?= $campo==='numero'?'maxlength="10"':'min="1" max="2147483647" step="1"' ?> value="<?= e($datos[$campo]) ?>" required <?= isset($errores[$campo])?'aria-invalid="true" aria-describedby="error-'.$campo.'"':'' ?>><?php if(isset($errores[$campo])): ?><small class="field-error" id="error-<?= $campo ?>"><?= e($errores[$campo]) ?></small><?php endif ?></div><?php endforeach ?>
<div><label for="estado">Estado *</label><select id="estado" name="estado" required><?php foreach(Habitacion::ESTADOS as $s): ?><option value="<?= $s ?>" <?= $datos['estado']===$s?'selected':'' ?>><?= e(ucfirst(strtolower($s))) ?></option><?php endforeach ?></select><?php if(isset($errores['estado'])): ?><small class="field-error"><?= e($errores['estado']) ?></small><?php endif ?></div>
<div class="full"><label for="observaciones">Observaciones</label><textarea id="observaciones" name="observaciones" rows="4" maxlength="255" placeholder="Características, equipamiento o motivo de mantenimiento…"><?= e($datos['observaciones']) ?></textarea><small class="muted">Hasta 255 caracteres.</small><?php if(isset($errores['observaciones'])): ?><small class="field-error"><?= e($errores['observaciones']) ?></small><?php endif ?></div></div><div class="form-actions"><button class="button primary" type="submit">Guardar habitación</button><a class="button secondary" href="habitaciones.php">Cancelar</a></div></form></section>
<aside class="help-panel"><span class="eyebrow">ANTES DE GUARDAR</span><h2>Un espacio bien registrado</h2><p>El número identifica a la habitación y debe ser único.</p><p>El piso y la capacidad deben ser números enteros mayores que cero.</p><?php if($accion==='editar'): ?><p><strong><?= (int)($datos['activos']??0) ?> residentes activos</strong> asignados. La capacidad debe permitir alojarlos.</p><?php endif ?><p>El estado se actualiza manualmente. La ocupación activa se consulta desde el módulo de residentes.</p></aside></div>
<?php elseif($accion === 'eliminar'): $bloqueada=($datos['estado']==='OCUPADA'||($datos['activos']??0)>0); ?>
<div class="heading"><div><div class="eyebrow">CONFIRMACIÓN</div><h1>Eliminar habitación <?= e($datos['numero']) ?></h1><p>Revisa la información antes de continuar.</p></div></div>
<section class="panel form-panel confirm"><h2>¿Eliminar esta habitación del inventario?</h2><p>Habitación <strong><?= e($datos['numero']) ?></strong> · Piso <?= e($datos['piso']) ?> · <?= e($datos['capacidad']) ?> plazas</p><p>Residentes activos: <strong><?= (int)($datos['activos']??0) ?></strong></p>
<?php if($bloqueada): ?><div class="message error">No se puede eliminar porque está ocupada o tiene residentes activos.</div><?php else: ?><p>Esta acción elimina el registro. Los residentes inactivos o egresados conservan sus fichas y quedan sin habitación, según la relación definida en la base de datos.</p><?php endif ?>
<form method="post"><?= csrf() ?><div class="form-actions"><button class="button danger" <?= $bloqueada?'disabled':'' ?>>Confirmar eliminación</button><a class="button secondary" href="habitaciones.php">Cancelar</a></div></form></section>
<?php endif ?>
<?php else: ?><a class="button secondary" href="habitaciones.php">Volver a intentar</a><?php endif ?>
<?php require __DIR__.'/../includes/footer.php'; ?>
